Traceback (most recent call last):
  File "summarize_pi.py", line 103, in <module>
    ComputePi().main()
  File "summarize_pi.py", line 89, in main
    pi_values = input_file.readlines()[1]
IndexError: list index out of range
error: argument input_csv: invalid ExistingFile value: '../Analysis/Bacteroides_faecis_58503/African/output_matrix.csv'

